sudo: required
services:
  - docker

before_install:
  - docker build -t tomglenn/docker-react -f Dockerfile.dev .

script:
  - docker run tomglenn/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-eu-west-2-751096083712
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY